[package]
name = "ruston"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
libc = "^0.2"
rb-sys = { version = "^0.9", features = ["link-ruby"] }
coffret = "0.0.3"
